---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: parent-apps-set
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/oybed/openshift-applicationset
        revision: HEAD
        files:
          - path: applications/*.yaml
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/oybed/openshift-applicationset
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops
