{{- range $serverName,$serverValues := .Values.bmh.servers }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $serverName }}-network-config-secret
  namespace: openshift-machine-api
type: Opaque
stringData:
  nmstate: |
{{- tpl ($.Files.Get (printf "configs/interfaces_%s.yaml" $serverValues.profile_type)) $serverValues | indent 4 }}
{{- end }}

